#!/usr/bin/env bash

# ===================================== #
# Linux CPU Monitor in bash
#
# Author:  Soumo Sarkar
# Email: soumosarkar.official@gmail.com
# ===================================== #

declare current=()
declare previous=()

# copy the data from the current current into the previous array
copy-data() {
  previous=()

  local key value

  for key in "${!current[@]}";
  do
    value=${current[$key]}
    previous[$key]=$value
  done
  
}

read_proc() {
  local key user nice system idle iowait
  local irq softirq steal guest guest_nice 

  local busy value num

  while read -r key user nice system idle iowait \
    irq softirq steal guest guest_nice; do
      
      # filter out everything but the cores
      if [[ $key != cpu* ]]; then
        continue
      elif [[ $key == 'cpu' ]]; then
        continue
      fi

      num=${key#cpu}

      busy=$(( user + nice + system + irq + softirq + steal + guest + guest_nice ))
      idle=$(( idle + iowait ))

      value="$busy $idle"

      current[$num]=$value
  done < /proc/stat
}

print-bar() {
  local key=$1

  local busy1 idle1 busy2 idle2
  read -r busy1 idle1 <<< "${previous[$key]}"
  read -r busy2 idle2 <<< "${current[$key]}"

  local busy=$(( busy2 - busy1 ))
  local idle=$(( idle2 - idle1))

  local total=$(( busy + idle ))
  local usage=$(( 1000 * busy / total ))

  local int=$(( usage / 10 ))
  local frac=$(( usage % 10 ))
  local perc=$int.$frac


  local bar_char='|'
  local empty_char=' '
  local length=50

  local num_bars=$(( usage * length / 1000 ))

  local i
  local s='['
  for ((i = 0; i < num_bars; i++)); do
    s+=$bar_char
  done
  for ((i = num_bars; i < length; i++)); do
    s+=$empty_char
  done
  s+=']'

  echo "$s cpu$key ($perc%)"
}

visualize-data() {
  local now
  printf -v now '%(%Y-%m-%dT%H:%M:%S%z)T'
  
  echo "CPU Usage on $HOSTNAME - $now"

  for key in "${!current[@]}"; do
    print-bar "$key"
  done
}

cleanup() {
  printf '\e[?1049l' # disable alternate buffer
  printf '\e[?25h' # show the cursor
  printf '\e[H' # move the cursor home
}

main() {
  read_proc
  echo 'waiting for data...'
  sleep 1

  trap cleanup EXIT

  printf '\e[?1049h' # enable alternate buffer
  printf '\e[?25l' # hide the cursor
  printf '\e[H' # move the cursor home

  local s
  while true; do
  	copy-data
	  read_proc
    
    s=${ visualize-data; }

    printf '\e[2J' # erase entire screen
    printf '\e[H' # move the cursor back home
	  echo -n "$s"

	  sleep 1
  done
}

main "$@"
